# Numpy array

- El array es la estructura central de `numpy`.
- Es indexado.


In [1]:
import numpy as np

In [15]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

Todo de 3 en 3

In [16]:
array[::3]

array([ 1,  4,  7, 10])

Posición final, es decir, el 1 pero del final

In [17]:
array[-1]

10

Los 3 elementos del final del array

In [18]:
array[-3:]

array([ 8,  9, 10])

In [19]:
np.array([i for i in range(1,11)])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Matriz

In [9]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Ahora fila 0, columna 2 <br>
__Nota:__ El indexado comienza en 0.

In [10]:
matriz[0,2]

3

Ahora, de fila 1 hasta fila 2

In [20]:
matriz[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])