# Tipos de datos en numpy

In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [4]:
array.dtype

dtype('int64')

Cambias de int64 a float(que son más utiles con redes neuronales).

In [6]:
array = np.array([1,2,3],dtype="float64")
array.dtype

dtype('float64')

Si ya tenía un de tipo entero, lo puedo cambiar directamente desde la biblioteca.

In [7]:
array = np.array([1,2,3,4])
array.dtype

dtype('int64')

In [11]:
array = array.astype(np.float64)
array.dtype

dtype('float64')

Cambiar a tipo boleano. Todos los ceros son `False`, cualquier otro número da `True`

In [14]:
array = np.array([0,1,2,3,4])
array = array.astype(np.bool_)
array

array([False,  True,  True,  True,  True])

Ahora entero como texto

In [16]:
array = np.array([0,1,2,3,4])
array = array.astype(np.string_)
print(array.dtype)
print(array)

|S21
[b'0' b'1' b'2' b'3' b'4']


Y ahora de string a número

In [17]:
array = np.array(['0','1','2'])
array = array.astype(np.int64)
print(array.dtype)
print(array)

int64
[0 1 2]


__Nota:__ En un array de numpy solo puedo tener un único tipo de dato.