# Dimensiones

In [1]:
import numpy as np

In [2]:
scalar = np.array(1)
scalar.ndim

0

In [6]:
vector = np.array([1,2,3])
vector.ndim

1

In [7]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz.ndim

2

In [8]:
tensor = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
tensor.ndim

3

In [9]:
tensor

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

# Agregar o eliminar dimensiones

In [13]:
vector = np.array([1,2,3], ndmin=10)
print(f'dimensiones={vector.ndim}')
print(f'vector = {vector}')

dimensiones=10
vector = [[[[[[[[[[1 2 3]]]]]]]]]]


- `axis=0` significa que es a nivel de filas
- `axis=1` significa columnas

Expandir una dimensión en el axis 0. 

In [18]:
np.expand_dims(np.array([1,2,3]), axis=0)

array([[1, 2, 3]])

In [19]:
np.expand_dims(np.array([1,2,3]), axis=1)

array([[1],
       [2],
       [3]])

Reducir la dimensionalidad, a la dimensión útil usando `squeeze`

In [21]:
vector = np.array([1,2,3], ndmin=10)
np.squeeze(vector)

array([1, 2, 3])