# Crear arrays

In [1]:
import numpy as np

Hacer un paralelo entre esto

In [2]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Pero usando `numpy`

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Usando un paso de 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
# 4 filas y 4 columnas, se pasan como una tupla
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Crear un array con valores aleatorios entre dos números

In [20]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

Matriz diagonal principal

In [18]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Más aleatorios

In [21]:
np.random.rand()

0.8605236447428223

In [22]:
np.random.rand(4)


array([0.05040823, 0.39063756, 0.46959272, 0.55750114])

In [26]:
# 4 filas y 3 columnas
np.random.rand(4,3)

array([[0.39670493, 0.38713757, 0.29134247],
       [0.09850685, 0.60079371, 0.0591625 ],
       [0.71016249, 0.35527905, 0.61758204],
       [0.46747405, 0.83523433, 0.88018458]])

In [28]:
# Número random entre 1 y 10
np.random.randint(1,10)

9

In [30]:
# Números entre 0 y 10 con 4 filas y 3 columnas
np.random.randint(0,10,(4,3))

array([[6, 1, 9],
       [1, 7, 1],
       [9, 4, 8],
       [9, 4, 3]])