# Shape y Reshape

In [1]:
import numpy as np

In [3]:
array = np.random.randint(1,10,(3,2))

In [10]:
array

array([[6, 4],
       [1, 3],
       [4, 9]])

In [5]:
# Dice cuántas filas y columnas tiene array.
array.shape

(3, 2)

Transforma `array` de 3 filas a 1 fila, y 2 columnas a 6 columnas

In [12]:
array.reshape(1,6)

array([[6, 4, 1, 3, 4, 9]])

In [13]:
# otro ejemplo
array.reshape(2,3)

array([[6, 4, 1],
       [3, 4, 9]])

También se puede aplicar así. 

In [14]:
np.reshape(array,(1,6))

array([[6, 4, 1, 3, 4, 9]])

In [23]:
array

array([[6, 4],
       [1, 3],
       [4, 9]])

Se puede hacer el reshape, recorriendo como lo hace C o como lo hace Fortran

In [25]:
# ordenar por filas
np.reshape(array,(2,3),'C')

array([[6, 4, 1],
       [3, 4, 9]])

In [26]:
# ordenar por columnas
np.reshape(array,(2,3),'F')

array([[6, 4, 3],
       [1, 4, 9]])