# Funciones principales de `numpy`

In [1]:
import numpy as np

In [9]:
array = np.random.randint(1,20,(2,5))

In [10]:
array

array([[ 4, 16, 15, 11,  6],
       [17, 19, 12,  9, 17]])

In [12]:
# máximo
array.max()

19

In [19]:
# máximo por 0,máximo por columnna
array.max(0)

array([17, 19, 15, 11, 17])

In [21]:
# máximo por 1,máximo por fila
array.max(1)

array([16, 19])

In [13]:
# mínimo
array.min()

4

In [31]:
array

array([[ 4, 16, 15, 11,  6],
       [17, 19, 12,  9, 17]])

In [34]:
# indice donde se encuentra valor más grande del array
# Nota: Muestra el primero que encuentra en caso de que hayan repetidos
print(array.argmax())
print(array.argmax(0)) # max por columna
print(array.argmax(1)) # max por fila


6
[1 1 0 0 1]
[1 1]


In [15]:
# promedio
array.mean()

12.6

In [35]:
# Diferencia entre valor más grande y el más pequeño, pico a pico
array.ptp()

15

Lo que es equivalente a 

In [36]:
array.max() - array.min()

15

In [42]:
array

array([[ 4, 16, 15, 11,  6],
       [17, 19, 12,  9, 17]])

In [51]:
print(np.percentile(array,75,axis=1)) # Por fila
print(np.percentile(array,50,axis=1))
print(np.percentile(array,25,axis=1))


[15. 17.]
[11. 17.]
[ 6. 12.]
