# Copy

Observar el siguiente error

In [1]:
import numpy as np

In [3]:
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
new = array[0:6]
new

array([0, 1, 2, 3, 4, 5])

In [6]:
new[:]=0

Aunque parecia que los cambios de hacían a `new` realmente se hicieron en el arraglo original `array`.

In [7]:
array

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

## Solución

In [14]:
array = np.arange(0,10)
array_copy = array.copy()
array_copy = array_copy[0:6]
array_copy

array([0, 1, 2, 3, 4, 5])

In [15]:
array_copy[:] = 0

In [16]:
array_copy

array([0, 0, 0, 0, 0, 0])

In [17]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Copy evita el problema de borrar datos en la estructura original.