# Condiciones

In [1]:
import numpy as np

In [6]:
array = np.arange(0,20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
# Aplicador directamente al arreglo
menores = array < 5
menores

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [12]:
## retorna únicamente los que están en True
array[menores]

array([0, 1, 2, 3, 4])

In [15]:
# Ojo: and no funciona, siempre usar &
array[(array>5) & (array < 10)]

array([6, 7, 8, 9])

In [16]:
# Asignar valor a los que cumplen una condición 
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
# Cambia por 20 todos los elementos que cumplen con la condición.
array[array>=15] = 20
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 20, 20,
       20, 20, 20])

In [22]:
# Muestra los que son pares
array[array%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 20, 20, 20, 20, 20])