# Operaciones

In [1]:
import numpy as np

In [15]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
array_2 = array.copy()

In [21]:
# Multiplica cada elemento del array por 2
array_3 = array_2*2

In [22]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
array + array_3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [26]:
matriz = np.random.randint(1,10,(3,2))
matriz

array([[9, 5],
       [2, 1],
       [9, 8]])

In [28]:
# Matriz transpuesta
matriz.T

array([[9, 2, 9],
       [5, 1, 8]])

In [32]:
matriz_2 = np.random.randint(1,10,(3,2))

In [35]:
# producto punto de dos arrays
np.matmul(matriz.T,matriz_2)

array([[72, 80],
       [51, 56]])

In [39]:
matriz.T

array([[9, 2, 9],
       [5, 1, 8]])

In [40]:
matriz_2

array([[2, 4],
       [9, 4],
       [4, 4]])

In [41]:
18+18+36

72